### ISSUE TITLE
The GNU General Public License in COPYING file is outdated

### ISSUE THREAD

**Issue by svalx** [iustin/mt-st#5]
Update it please from [The GNU General Public License version 2](http://www.gnu.org/licenses/old-licenses/gpl-2.0.txt)

**Comment by iustin** [comment]
The current license seems to be the old version (with old FSF address) of the kernel's COPYING. Updating it to the FSF gpl-v2 would lose the kernel notice header, but there are no other diffs. Updating it to the current kernel's COPYING would introduce the smallest changes.

Since currently the repository still includes `mtio.h` from the kernel sources, I think we should keep the kernel notice (i.e. the code is GPL v2 exactly, and not "or later"). @kmakisara, what do you think?

**Comment by kmakisara** [comment]
> On 1.5.2016, at 4.45, Iustin Pop notifications@github.com wrote:
> 
> The current license seems to be the old version (with old FSF address) of the kernel's COPYING. Updating it to the FSF gpl-v2 would lose the kernel notice header, but there are no other diffs. Updating it to the current kernel's COPYING would introduce the smallest changes.
> 
> Since currently the repository still includes mtio.h from the kernel sources, I think we should keep the kernel notice (i.e. the code is GPL v2 exactly, and not "or later"). @kmakisara, what do you think?
> 
> Sounds good.

Thanks,
Kai
